### ISSUE TITLE
Troposphere 2.1.0 may have broke something.

### ISSUE THREAD

**Issue by stevengorrell** [rackerlabs/jetstream#71]
This template compiles fine, but breaks during testing.

```
'''CodeCommit Template'''

import random
import string

from troposphere import (AWS_NO_VALUE, If, Equals, GetAtt,
                         Not, Output, Ref, codecommit)

from faws_templates.base import FAWSParameter, FAWSTemplate
from faws_templates.common import params


class CodeCommit(FAWSTemplate):
    '''CodeCommit Template'''

    def __init__(self):
        super(CodeCommit, self).__init__('codecommit.template')
        template = self.template
        template.add_description(self.name + " - Creates an AWS CodeCommit repository. Please be aware that this template will create resources for which you will be charged.")

        template.add_parameter(params.environment)

        repo_parameter_group = "Repository Configuration"
        trigger_1_parameter_group = "Trigger 1 Configuration (OPTIONAL)"

        suffix = ''.join(random.SystemRandom().choice(string.ascii_lowercase + string.digits) for _ in range(5))
        test_repo_name = "test-repo-{}".format(suffix)

        repo_name = template.add_parameter(FAWSParameter(
            "RepositoryName",
            AllowedPattern="([A-Za-z0-9._-]+)",
            Default="MyRepo",
            Type="String",
            Description="A name for the AWS CodeCommit repository. Must contain only letters, numbers, periods (.), underscores (_), and dashes (-). Maximum length 100.",
            GroupName=repo_parameter_group,
            TestParameter=(test_repo_name),
        ))

        repo_description = template.add_parameter(FAWSParameter(
            "RepositoryDescription",
            Default="Created with CloudFormation.",
            Type="String",
            Description="A detailed description for the AWS CodeCommit repository.",
            GroupName=repo_parameter_group,
            TestParameter=("Testing"),
        ))

        enable_trigger_1 = template.add_parameter(FAWSParameter(
            "Trigger1Enable",
            Default="False",
            Type="String",
            AllowedValues=["True", "False"],
            Label="Enable Trigger",
            GroupName=trigger_1_parameter_group,
            TestParameter=("True"),
        ))

        template.add_condition("isTrigger1Enable", Equals(Ref(enable_trigger_1), "True"))

        trigger_1_name = template.add_parameter(FAWSParameter(
            "Trigger1Name",
            Default="Trigger1",
            AllowedPattern="([A-Za-z0-9._-]+)",
            Description="The name of the trigger. Can only contain numbers, periods (.), underscores (_), and dashes (-). Maximum length 100.",
            Type="String",
            Label="Trigger Name",
            GroupName=trigger_1_parameter_group,
            TestParameter=("Test_Trigger"),
        ))

        trigger_1_custom_data = template.add_parameter(FAWSParameter(
            "Trigger1CustomData",
            Default="",
            Type="String",
            Description="Any custom data associated with the trigger that will be included in the information sent to the target of the trigger.",
            GroupName=trigger_1_parameter_group,
            TestParameter=("Testing"),
        ))

        template.add_condition("isCustomData1Set", Not(Equals(Ref(trigger_1_custom_data), "")))

        trigger_1_destination_arn = template.add_parameter(FAWSParameter(
            "Trigger1DestinationArn",
            Type="String",
            Description="REQUIRED. The ARN of the SNS Topic, or SQS Queue that is the target for a trigger. Full ARN required.",
            Label="Notification ARN",
            GroupName=trigger_1_parameter_group,
            TestParameter=("arn:aws:sns:us-west-2:891714082543:rackspace-support")
        ))

        trigger_1_branches = template.add_parameter(FAWSParameter(
            "Trigger1Branches",
            Type="CommaDelimitedList",
            Default="Master",
            Description="Comma Delimited List of branch names. Maximum length 256",
            GroupName=trigger_1_parameter_group,
            TestParameter=("Master"),
        ))

        trigger_1_events = template.add_parameter(FAWSParameter(
            "Trigger1Events",
            Default="all",
            Type="CommaDelimitedList",
            Description="Comma delimited list of Valid Values: \"all\", \"updateReference\", \"createReference\", \"deleteReference\". The value \"all\" cannot be used with any other values.",
            GroupName=trigger_1_parameter_group,
            TestParameter=("updateReference", "createReference"),
        ))

        repo_trigger1 = codecommit.Trigger(
            Name=Ref(trigger_1_name),
            CustomData=If("isCustomData1Set", Ref(trigger_1_custom_data), Ref(AWS_NO_VALUE)),
            DestinationArn=Ref(trigger_1_destination_arn),
            Branches=Ref(trigger_1_branches),
            Events=Ref(trigger_1_events),
        )

        repo = self.template.add_resource(codecommit.Repository(
            "Repository",
            RepositoryName=Ref(repo_name),
            RepositoryDescription=Ref(repo_description),
            Triggers=If("isTrigger1Enable", [repo_trigger1], Ref(AWS_NO_VALUE)),
        ))

        template.add_output(Output(
            "RepoName",
            Description="CodeCommit Repository Name",
            Value=GetAtt(repo, "Name")
        ))

        template.add_output(Output(
            "RepoARN",
            Description="CodeCommit Repository ARN",
            Value=GetAtt(repo, "Arn")
        ))

        template.add_output(Output(
            "CloneHTTP",
            Description="The URL to use for cloning the repository over HTTPS",
            Value=GetAtt(repo, "CloneUrlHttp")
        ))

        template.add_output(Output(
            "CloneSSH",
            Description="The URL to use for cloning the repository over SSH",
            Value=GetAtt(repo, "CloneUrlSsh")
        ))
```

Output without --test
```
E:\Github\TroposphereTemplates [codecommitfix]> jetstream -m faws_templates
Updated Templates: codecommit.template
```

Output with --test
```
E:\Github\TroposphereTemplates [codecommitfix]> jetstream --test -m faws_templates
Updated Templates: codecommit.template
Traceback (most recent call last):
  File "E:\Github\jetstream\venv\Scripts\jetstream-script.py", line 11, in <module>
    load_entry_point('jetstream', 'console_scripts', 'jetstream')()
  File "e:\github\jetstream\jetstream\cli.py", line 170, in main
    _execute(args)
  File "e:\github\jetstream\jetstream\cli.py", line 62, in _execute
    test = testing.Test(updated_templates, dry_run=args.dry_test)
  File "e:\github\jetstream\jetstream\testing.py", line 40, in __init__
    self.templates = _flatten_templates(templates)
  File "e:\github\jetstream\jetstream\testing.py", line 229, in _flatten_templates
    return _recurse_dependencies(templates).values()
  File "e:\github\jetstream\jetstream\testing.py", line 242, in _recurse_dependencies
    if test_param_group.dependencies():
  File "e:\github\jetstream\jetstream\template.py", line 129, in dependencies
    deps[source.name] = source
AttributeError: 'str' object has no attribute 'name'
```

Let me know if I can provide more information or assist in any way.

**Comment by martinb3** [comment]
I think this is due to the following parameter:

def __init__(self, name, value, source=None, source_set_name=None):

**Comment by martinb3** [comment]
I think this is due to the following `trigger_1_events` parameter:

```
        trigger_1_events = template.add_parameter(FAWSParameter(
            "Trigger1Events",
            Default="all",
            Type="CommaDelimitedList",
            Description="Comma delimited list of Valid Values: \"all\", \"updateReference\", \"createReference\", \"deleteReference\". The value \"all\" cannot be used with any other values.",
            GroupName=trigger_1_parameter_group,
            TestParameter=("updateReference", "createReference"),
        ))
```

The constructor for TestParameter is:
```
def init(self, name, value, source=None, source_set_name=None):
```

`source` must be a template, not a string, but it's being passed a string.

**Comment by martinb3** [comment]
Perhaps this should be: ```TestParameter=("updateReference,createReference"),```?
